version: '2'

services:

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9092:9092"
      - "9000:9000"
#    environment:
#      SONARQUBE_JDBC_USERNAME: 'sonar'
#      SONARQUBE_JDBC_PASSWORD: 'sonar'
#      SONARQUBE_JDBC_URL: 'jdbc:postgresql://localhost/sonar'
    restart: always
