version: "3"

services:

  cadvisor:
    image: google/cadvisor
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:v2.3.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - 9100:9100
#    network_mode: host

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    volumes:
      - ./prometheus/blackbox.yml:/etc/blackbox_exporter/blackbox.yml

  grafana:
    image: grafana/grafana:5.1.1
    ports:
      - 3000:3000
    volumes:
      #- ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=http://grafana.foo
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

volumes:
  grafana-data: {}
