version: "2"

services:

  cadvisor:
    image: google/cadvisor
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  metrics-gateway:
    image: prom/pushgateway
    ports:
      - 127.0.0.1:9091:9091

  prometheus:
    image: prom/prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - 9100

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 127.0.0.1:9115:9115
    volumes:
      - ./prometheus/blackbox.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
