version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    environment:
      - TZ=Europe/Berlin
      - PLEX_CLAIM=claim-d76ddzRhc2zXgwzMq8gW
      - ADVERTISE_IP=http://185.207.104.161:32400/
    hostname: PlexServer
    volumes:
      - config:/config
      - transcode:/transcode
      - /opt/media:/data
volumes:
  config: {}
  transcode: {}
