version: '2'

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
    environment:
        GF_USERS_ALLOW_SIGN_UP: 'false'
    restart: always

volumes:
  grafana:
