version: '2'
services:
  jenkins:
    image: jenkins
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
#     - "/var/docker/jenkins/data:/var/lib/jenkins/"
      - "jenkins:/var/lib/jenkins"
    restart: always
volumes:
  jenkins: {}
