gitlab:
  image: 'gitlab/gitlab-ce:latest'
  container_name: gitlab
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
#  volumes:
#    - config:/etc/gitlab
#    - logs:/var/log/gitlab
#    - data:/var/opt/gitlab

#volumes:
#    data: {}
#    logs: {}
#    data: {}
